/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoutsRouteImport } from './routes/couts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecettesIndexRouteImport } from './routes/recettes.index'
import { Route as RecettesIdRouteImport } from './routes/recettes.$id'

const CoutsRoute = CoutsRouteImport.update({
  id: '/couts',
  path: '/couts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecettesIndexRoute = RecettesIndexRouteImport.update({
  id: '/recettes/',
  path: '/recettes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecettesIdRoute = RecettesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecettesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/couts': typeof CoutsRoute
  '/recettes/$id': typeof RecettesIdRoute
  '/recettes/': typeof RecettesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/couts': typeof CoutsRoute
  '/recettes/$id': typeof RecettesIdRoute
  '/recettes': typeof RecettesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/couts': typeof CoutsRoute
  '/recettes/$id': typeof RecettesIdRoute
  '/recettes/': typeof RecettesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/couts' | '/recettes/$id' | '/recettes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/couts' | '/recettes/$id' | '/recettes'
  id: '__root__' | '/' | '/auth' | '/couts' | '/recettes/$id' | '/recettes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CoutsRoute: typeof CoutsRoute
  RecettesIndexRoute: typeof RecettesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/couts': {
      id: '/couts'
      path: '/couts'
      fullPath: '/couts'
      preLoaderRoute: typeof CoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recettes/': {
      id: '/recettes/'
      path: '/recettes'
      fullPath: '/recettes/'
      preLoaderRoute: typeof RecettesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recettes/$id': {
      id: '/recettes/$id'
      path: '/$id'
      fullPath: '/recettes/$id'
      preLoaderRoute: typeof RecettesIdRouteImport
      parentRoute: typeof RecettesRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CoutsRoute: CoutsRoute,
  RecettesIndexRoute: RecettesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
