/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecettesRouteImport } from './routes/recettes'
import { Route as CoutsRouteImport } from './routes/couts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecettesIdRouteImport } from './routes/recettes.$id'

const RecettesRoute = RecettesRouteImport.update({
  id: '/recettes',
  path: '/recettes',
  getParentRoute: () => rootRouteImport,
} as any)
const CoutsRoute = CoutsRouteImport.update({
  id: '/couts',
  path: '/couts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecettesIdRoute = RecettesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecettesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/couts': typeof CoutsRoute
  '/recettes': typeof RecettesRouteWithChildren
  '/recettes/$id': typeof RecettesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/couts': typeof CoutsRoute
  '/recettes': typeof RecettesRouteWithChildren
  '/recettes/$id': typeof RecettesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/couts': typeof CoutsRoute
  '/recettes': typeof RecettesRouteWithChildren
  '/recettes/$id': typeof RecettesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/couts' | '/recettes' | '/recettes/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/couts' | '/recettes' | '/recettes/$id'
  id: '__root__' | '/' | '/auth' | '/couts' | '/recettes' | '/recettes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CoutsRoute: typeof CoutsRoute
  RecettesRoute: typeof RecettesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recettes': {
      id: '/recettes'
      path: '/recettes'
      fullPath: '/recettes'
      preLoaderRoute: typeof RecettesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/couts': {
      id: '/couts'
      path: '/couts'
      fullPath: '/couts'
      preLoaderRoute: typeof CoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recettes/$id': {
      id: '/recettes/$id'
      path: '/$id'
      fullPath: '/recettes/$id'
      preLoaderRoute: typeof RecettesIdRouteImport
      parentRoute: typeof RecettesRoute
    }
  }
}

interface RecettesRouteChildren {
  RecettesIdRoute: typeof RecettesIdRoute
}

const RecettesRouteChildren: RecettesRouteChildren = {
  RecettesIdRoute: RecettesIdRoute,
}

const RecettesRouteWithChildren = RecettesRoute._addFileChildren(
  RecettesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CoutsRoute: CoutsRoute,
  RecettesRoute: RecettesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
